export const REQUEST_DPS = 'REQUEST_DPS';
export const REQUEST_DPS_DONE = 'DATA_SUCCEEDED';
export const REQUEST_DPS_FAILED = 'DATA_FAILED';
export const SHOW_WELCOME = 'SHOW_WELCOME';
export const MAP_DATE_CHANGE = 'MAP_DATE_CHANGE';