export const REQUEST_DPS = 'REQUEST_DPS';
export const REQUEST_DPS_DONE = 'DATA_SUCCEEDED';
export const REQUEST_DPS_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';
export const SHOW_WELCOME = 'SHOW_WELCOME';