export const About: React.FC<{}> = () => {
  return (
    <>
      <h1>About UMICH DPS Project</h1>
      <p>
        The{" "}
        <a href="http://clerycenter.org/summary-jeanne-clery-act">Clery Act</a>{" "}
        dictates that all federally funded universities share information about
        crimes that occur on campus. The{" "}
        <a href="http://www.dpss.umich.edu/crime-log/">crime log</a> for the
        University of Michigan leaves some wanting, so this website is an
        alternative take on the data. Some of the niceties you’ll find here:
      </p>
      <ul>
        <li>Quick and responsive (data loads faster)</li>
        <li>Maps to pinpoint incidents</li>
        <li>Statistics to draw fun interpretations from</li>
      </ul>
      <p>
        Perhaps most importantly, this is/was a side project to try my hand at
        modern web development. I welcome everyone to examine (contribute!?) to
        the code{" "}
        <a href="https://github.com/nickbabcock/udps">over on Github</a>.
      </p>
      <p>
        The data is generated by downloading the previous day’s incidents and
        appending it to a running list of incidents, and by offloading the data,
        the backend server for the DPS’s won’t be stressed every serving
        additional requests.
      </p>
      <p>
        I previously created{" "}
        <a href="https://umich.nbsoftsolutions.com">another site</a> with a
        similar purpose only it was architected slightly different (focused
        mainly server-side). The old site also gathered data by manually
        scraping the police department’s site because their JSON API had not
        been constructed. Rethinking the site, I decided to focus more on
        offline capabilities and user experience. Hopefully, I’ve succeeded.
      </p>
      <p>
        Why is this site focused on the University of Michigan? Well, it’s my
        alma mater!
      </p>
    </>
  );
};
